name: arru-seismic-backprojection

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python>=3.6
  - anaconda
  - pip
  - matplotlib
  - pandas
  - numpy     
  - tensorflow-gpu=2.4
  - mpi4py=3.0.3
  - numba=0.51.2
  - pip:
    - obspy=1.2.2
    - tensorflow-addons
